import type { AppIconKey } from "./provider";

// Thumbnails for the in-app App-icon picker — the SAME PNGs baked into the
// binary as alternate icons (generated by scripts/gen-icons.mjs). require() (not
// import) keeps this CI-safe with no *.png type declaration, matching
// src/components/gift-logo.tsx.
export const ICON_PREVIEWS: Record<AppIconKey, number> = {
  signature: require("../../assets/app-icons/signature.png"),
  birthdayBash: require("../../assets/app-icons/birthdayBash.png"),
  sweetBeginnings: require("../../assets/app-icons/sweetBeginnings.png"),
  modernRomance: require("../../assets/app-icons/modernRomance.png"),
  winterFrost: require("../../assets/app-icons/winterFrost.png"),
  cabinCozy: require("../../assets/app-icons/cabinCozy.png"),
  firesideCozy: require("../../assets/app-icons/firesideCozy.png"),
  northernLights: require("../../assets/app-icons/northernLights.png"),
  mountainChalet: require("../../assets/app-icons/mountainChalet.png"),
};
